# Generated by Django 4.1.13 on 2024-02-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('named_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='наименование URL')),
                ('menu_name', models.CharField(max_length=50, verbose_name='наименование меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
                'ordering': ('pk',),
            },
        ),
    ]
